### ISSUE TITLE
Hard Coded "\" in URL

### ISSUE THREAD

**Issue by Sprawlie** [bakito/adguardhome-sync#126]
There is a hard coded "\\" character in the URL generator for the origin status.

The Following configuration is unable to connect to an adguard instance:

```
origin:
  # url of the origin instance
  url: http://192.168.0.3:3000
  apiPath: /control
  # insecureSkipVerify: true # disable tls check
  username: <user>
  password: <password>
```

the result of all attempts puts the following:
`{"from": "192.168.0.3:3000", "error": ": Get \"http://192.168.0.3:3000/control/status\": dial tcp 192.168.0.3:3000: connect: no route to host"}`

As you can see, there is a "\\" character being added to the URL path. I have verified that AdGuard does NOT support this URL and fails.

there should be no trailing slashes on the URL and the "/control/status" IS the correct URL.
