### ISSUE TITLE
DHCP Info not copied

### ISSUE THREAD

**Issue by namirda** [bakito/adguardhome-sync#149]
**Description of problem:**
aguardhome-sync does not sync dhcp settings and static leases although other settings are copied successfully

No error messages obvious in error log - sync of dhcp parameters does not seem to be attempted.

After sync, the dhcp in the replica is disabled and the dhcp interface is deselected even if dhcp in the origin is enabled.

**Steps to reproduce the behavior:**
1. What version of AdGuardHome sync used? 0.4.11
2. What version of AdGuardHome us used? 0.107.23
3. How does the configuration look? See attached config file
4. What is the error message? No error message. See attached log file

[config.txt](https://github.com/bakito/adguardhome-sync/files/10660119/config.txt)
[adguard_sync_logs.txt](https://github.com/bakito/adguardhome-sync/files/10660140/adguard_sync_logs.txt)

Thanks for your help.

**Comment by bakito** [comment]
Hi @namirda 

Can you please try the following config for the replica and add the **interfaceName** for the replica?

```yaml
replica:
  # url of the replica instance
  url: http://192.168.1.201:80
  insecureSkipVerify: true
  username: nnnn
  password: xxxxxxxx
  interfaceName: eth0
```
This is needed, as the network interface of the replica can not be evaluated by agd-sync.
