### ISSUE TITLE
Question: What is the basic auth for regarding the api section in the config file?

### ISSUE THREAD

**Issue by miguelarios** [bakito/adguardhome-sync#172]
What is the credentials referring to regarding the api section? Is this with the origin or replica or the adguardhome-sync docker itself?

```
api:
  # Port, default 8080
  port: 8080
  # if username and password are defined, basic auth is applied to the sync API 
  username: username
  password: password
```
