### ISSUE TITLE
Sync fails when replica url has port

### ISSUE THREAD

**Issue by mvdkleijn** [bakito/adguardhome-sync#182]
**Describe the bug**
When a port is added to the replica URL, the system breaks with an "invalid IP is not an IPv4 address". See below.

**To Reproduce**
1. What version of AdGuardHome sync used? **v0.4.13 (2023-03-07T17:28:45Z)**
2. What version of AdGuardHome us used? **v0.107.27**
3. How does the configuration look?

```
---
services:
  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync
    container_name: adguardhome-sync
    command: run
    environment:
      LOG_LEVEL: 'info'
      ORIGIN_URL: 'http://192.168.2.20:8800'
      ORIGIN_USERNAME: '*******'
      ORIGIN_PASSWORD: '*******'
      REPLICA_URL: 'http://192.168.2.21:8800'
      REPLICA_USERNAME: '*******'
      REPLICA_PASSWORD: '*******'
      CRON: '*/10 * * * *' # run every 10 minutes
      RUNONSTART: true
      API_PORT: 8080
    ports:
      - 8080:8080
    restart: unless-stopped
```

5. What is the error message?

```
adguardhome-sync  | 2023-04-12T16:24:31.404Z	INFO	sync	sync/sync.go:29	AdGuardHome sync	{"version": "v0.4.13", "build": "2023-03-07T17:28:45Z"}
adguardhome-sync  | 2023-04-12T16:24:31.404Z	INFO	sync	sync/sync.go:55	Setup cronjob	{"cron": "*/10 * * * *", "next-execution": "2023-04-12T16:30:00.000Z"}
adguardhome-sync  | 2023-04-12T16:24:31.404Z	INFO	sync	sync/http.go:52	Starting API server	{"port": 8080}
adguardhome-sync  | 2023-04-12T16:24:31.405Z	INFO	sync	sync/sync.go:65	Running sync on startup
adguardhome-sync  | 2023-04-12T16:24:31.564Z	INFO	sync	sync/sync.go:113	Connected to origin	{"from": "192.168.2.20:8800", "version": "v0.107.27"}
adguardhome-sync  | 2023-04-12T16:24:33.369Z	INFO	sync	sync/sync.go:198	Start sync	{"from": "192.168.2.20:8800", "to": "192.168.2.21:8800"}
adguardhome-sync  | 2023-04-12T16:24:33.497Z	INFO	sync	sync/sync.go:206	Connected to replica	{"from": "192.168.2.20:8800", "to": "192.168.2.21:8800", "version": "v0.107.27"}
adguardhome-sync  | 2023-04-12T16:24:35.056Z	INFO	client	client/client.go:472	Set dhcp server config	{"host": "192.168.2.21:8800"}
adguardhome-sync  | 2023-04-12T16:24:35.184Z	ERROR	sync	sync/sync.go:263	Error syncing dns	{"from": "192.168.2.20:8800", "to": "192.168.2.21:8800", "error": "400 Bad Request(bad dhcpv4 configuration: dhcpv4: invalid IP is not an IPv4 address\n)"}
adguardhome-sync  | github.com/bakito/adguardhome-sync/pkg/sync.(*worker).syncTo
adguardhome-sync  | 	/go/src/app/pkg/sync/sync.go:263
adguardhome-sync  | github.com/bakito/adguardhome-sync/pkg/sync.(*worker).sync
adguardhome-sync  | 	/go/src/app/pkg/sync/sync.go:186
adguardhome-sync  | github.com/bakito/adguardhome-sync/pkg/sync.Sync.func3
adguardhome-sync  | 	/go/src/app/pkg/sync/sync.go:66
```

**Expected behavior**
I expected a successful sync.
