### ISSUE TITLE
400 Bad Request error syncing filters

### ISSUE THREAD

**Issue by svh1985** [bakito/adguardhome-sync#21]
**Describe the bug**
400 Bad Request error syncing filters.

**To Reproduce**
1. What version of AdGuardHome sync used? v0.3.0-rc1 Docker Container
2. What version of AdGuardHome us used? Version: v0.106.3
3. How does the configuration look?
```
# cron expression to run in daemon mode. (default; "" = runs only once)
cron: ""

# runs the synchronisation on startup
runOnStart: true

origin:
  # url of the origin instance
  url: http://172.16.0.2:81


# replica instance (optional, if only one)
replica:
  # url of the replica instance
  url: http://172.16.0.3
  username: usr
  password: psw
```

4. What is the error message? 

```
2021-06-02T19:29:43.627Z	INFO	sync	sync/http.go:65	Starting API server	{"version": "v0.3.0-rc1", "port": 8080}

2021-06-02T19:40:10.843Z	INFO	root	cmd/root.go:102	Using config file:/config/adguardhome-sync.yaml

2021-06-02T19:40:10.844Z	INFO	sync	sync/sync.go:56	Run on startup	{"version": "v0.3.0-rc1"}

2021-06-02T19:40:10.933Z	INFO	sync	sync/sync.go:181	Start sync	{"from": "172.16.0.2:81", "to": "172.16.0.3"}

2021-06-02T19:40:11.436Z	INFO	client	client/client.go:239	Add filter	{"host": "172.16.0.3", "url": "https://hosts-file.net/ad_servers.txt", "whitelist": false, "enabled": false}

2021-06-02T19:40:11.969Z	ERROR	sync	sync/sync.go:212	Error syncing filters	{"from": "172.16.0.2:81", "to": "172.16.0.3", "error": "400 Bad Request"}

github.com/bakito/adguardhome-sync/pkg/sync.(*worker).syncTo

	/go/src/app/pkg/sync/sync.go:212

github.com/bakito/adguardhome-sync/pkg/sync.(*worker).sync

	/go/src/app/pkg/sync/sync.go:168

github.com/bakito/adguardhome-sync/pkg/sync.Sync

	/go/src/app/pkg/sync/sync.go:57

github.com/bakito/adguardhome-sync/cmd.glob..func1

	/go/src/app/cmd/run.go:23

github.com/spf13/cobra.(*Command).execute

	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852

github.com/spf13/cobra.(*Command).ExecuteC

	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960

github.com/spf13/cobra.(*Command).Execute

	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897

github.com/bakito/adguardhome-sync/cmd.Execute

	/go/src/app/cmd/root.go:60


n

	/go/src/app/main.go:6

runtime.main

	/usr/local/go/src/runtime/proc.go:225

2021-06-02T19:40:11.969Z	INFO	sync	sync/http.go:65	Starting API server	{"version": "v0.3.0-rc1", "port": 8080}
```
