### ISSUE TITLE
v0.6.0 not honoring configuration file settings

### ISSUE THREAD

**Issue by ekrunch** [bakito/adguardhome-sync#271]
### What happened?

After the upgrade to 0.6.0, the application started throwing TLS errors even though I have insecureSkipVerify set to true in the configuration. It was working properly until the container image was updated.

After some playing around, I noticed there are several options in my configuration file that are not being honored (or not represented in PRINT_CONFIG_ONLY mode), but some are. Some settings are being honored, just not all of them.  I've checked the documentation and update notes for 0.6.0 and feel like I have everything right but maybe I missed something.

If I set properties like insecureSkipVerify with environment variables, the application works as expected. If I revert to the configuration file only, the new version does not work correctly.

### AdguardHome-Sync Version

v0.6.0

### AdguardHome Version

 v0.107.43

### Configuration

```shell
Using docker-compose on Debian 11 Bullesys / Raspberry Pi 4 hardware (stock Debian docker / compose packages), here is the compose file.

docker-compose YAML

---
version: "3.7"
services:
  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync
    container_name: adguardhome-sync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - CONFIGFILE=/config/adguardhome-sync.yaml #optional
      - PRINT_CONFIG_ONLY=true
    volumes:
      - /home/whadmin/Code/container-configurations/docker/compose/adguardhome-sync/config:/config
    restart: always
```

AdGuardHome-Sync configuration file
```
# cron expression to run in daemon mode. (default; "" = runs only once)
cron: "*/15 * * * *"

# runs the synchronisation on startup
runOnStart: true

origin:
  # url of the origin instance
  url: https://originhostname:443
  # apiPath: define an api path if other than "/control"
  insecureSkipVerify: true # disable tls check
  username: whadmin
  password: *********

# replica instance (optional, if only one)
replica:
  # url of the replica instance
  url: https://replicahostname:443
  # apiPath: define an api path if other than "/control"
  insecureSkipVerify: true # disable tls check
  username: whadmin
  password: *********

# Configure the sync API server, disabled if api port is 0
api:
  # Port, default 8080
  port: 0
  # if username and password are defined, basic auth is applied to the sync API
  #username: admin
  #password: 

# Configure sync features; by default all features are enabled.
features:
  generalSettings: true
  queryLogConfig: true
  statsConfig: true
  clientSettings: true
  services: true
  filters: true
  dhcp:
    serverConfig: false
    staticLeases: false
  dns:
    serverConfig: true
    accessLists: true
    rewrites: true
```

Output from running in PRINT_CONFIG_ONLY mode. It doesn't seem to honor the insecureSkipVerify, runOnStart, nor the DHCP config replication settings.
```
Creating network "adguardhome-sync_default" with the default driver
Creating adguardhome-sync ... done
Attaching to adguardhome-sync
adguardhome-sync    | 2024-01-12T10:53:45.621-0600      INFO    root    cmd/root.go:119 Using config file:/config/adguardhome-sync.yaml
adguardhome-sync    | 2024-01-12T10:53:45.627-0600      INFO    run     cmd/run.go:35   Printing adguardhome-sync config (THE APPLICATION WILL NOT START IN THIS MODE):
adguardhome-sync    | origin:
adguardhome-sync    |     url: https://originhostname:443
adguardhome-sync    |     webURL: https://originhostname:443
adguardhome-sync    |     apiPath: /control
adguardhome-sync    |     username: whadmin
adguardhome-sync    |     password: *********
adguardhome-sync    |     insecureSkipVerify: false
adguardhome-sync    |     autoSetup: false
adguardhome-sync    | replica:
adguardhome-sync    |     url: https://replicahostname:443
adguardhome-sync    |     webURL: ""
adguardhome-sync    |     apiPath: /control
adguardhome-sync    |     username: whadmin
adguardhome-sync    |     password: *********
adguardhome-sync    |     insecureSkipVerify: false
adguardhome-sync    |     autoSetup: false
adguardhome-sync    | cron: '*/15 * * * *'
adguardhome-sync    | runOnStart: true
adguardhome-sync    | printConfigOnly: true
adguardhome-sync    | features:
adguardhome-sync    |     dns:
adguardhome-sync    |         accessLists: true
adguardhome-sync    |         serverConfig: true
adguardhome-sync    |         rewrites: true
adguardhome-sync    |     dhcp:
adguardhome-sync    |         serverConfig: true
adguardhome-sync    |         staticLeases: true
adguardhome-sync    |     generalSettings: true
adguardhome-sync    |     queryLogConfig: true
adguardhome-sync    |     statsConfig: true
adguardhome-sync    |     clientSettings: true
adguardhome-sync    |     services: true
adguardhome-sync    |     filters: true
adguardhome-sync    |
```
```


### Relevant log output

```shell
adguardhome-sync    | 2024-01-12T11:08:55.530-0600      INFO    root    cmd/root.go:119 Using config file:/config/adguardhome-sync.yaml
adguardhome-sync    | 2024-01-12T11:08:55.543-0600      INFO    sync    sync/sync.go:38 AdGuardHome sync        {"version": "v0.6.0", "build": "2024-01-10T18:53:37Z", "os": "linux", "arch": "arm64"}
adguardhome-sync    | 2024-01-12T11:08:55.544-0600      DEBUG   sync    types/types.go:73       Using config    {"config": {"origin":{"url":"https://originhostname:443","webURL":"https://originhostname:443","apiPath":"/control","username":"w***n","password":"g****","insecureSkipVerify":false,"autoSetup":false},"replica":{"url":"https://replicahostname:443","webURL":"","apiPath":"/control","username":"w***n","password":"g****","insecureSkipVerify":false,"autoSetup":false},"cron":"*/15 * * * *","runOnStart":true,"api":{},"features":{"dns":{"accessLists":true,"serverConfig":true,"rewrites":true},"dhcp":{"serverConfig":true,"staticLeases":true},"generalSettings":true,"queryLogConfig":true,"statsConfig":true,"clientSettings":true,"services":true,"filters":true}}}
adguardhome-sync    | 2024-01-12T11:08:55.545-0600      INFO    sync    sync/sync.go:65 Setup cronjob   {"cron": "*/15 * * * *", "next-execution": "2024-01-12T11:15:00.000-0600"}
adguardhome-sync    | 2024-01-12T11:15:00.000-0600      DEBUG   client  client/client-methods.go:17     do get  {"host": "originhostname:443", "method": "GET", "path": "status", "username": "whadmin"}
adguardhome-sync    | 2024-01-12T11:15:00.152-0600      DEBUG   client  client/client-methods.go:27     error in do get {"host": "originhostname:443", "method": "GET", "path": "status", "username": "whadmin", "status": 0, "body": "", "error": "Get \"https://originhostname:443/control/status\": tls: failed to verify certificate: x509: certificate signed by unknown authority"}
adguardhome-sync    | 2024-01-12T11:15:00.152-0600      ERROR   sync    sync/sync.go:163        Error getting origin status     {"from": "originhostname:443", "error": ": Get \"https://originhostname:443/control/status\": tls: failed to verify certificate: x509: certificate signed by unknown authority"}
adguardhome-sync    | github.com/bakito/adguardhome-sync/pkg/sync.(*worker).sync
adguardhome-sync    |   /go/src/app/pkg/sync/sync.go:163
adguardhome-sync    | github.com/bakito/adguardhome-sync/pkg/sync.Sync.func2
adguardhome-sync    |   /go/src/app/pkg/sync/sync.go:59
adguardhome-sync    | github.com/robfig/cron/v3.FuncJob.Run
adguardhome-sync    |   /go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136
adguardhome-sync    | github.com/robfig/cron/v3.(*Cron).startJob.func1
adguardhome-sync    |   /go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312
```
