### ISSUE TITLE
While parsing config: yaml: line 15: did not find expected key

### ISSUE THREAD

**Issue by travisboss** [bakito/adguardhome-sync#28]
**Describe the bug**
Using the linuxserver version and getting this error when I start up my instances I have one instance at 254 and another at 250 I am going from main 254 to 250 and updated the port on the second instance to `3000`.  Both instances are install on bare metal raspberry pi's(3b+ and zero).
```
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 50-config: executing...
[cont-init.d] 50-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
While parsing config: yaml: line 15: did not find expected key
While parsing config: yaml: line 15: did not find expected key
While parsing config: yaml: line 15: did not find expected key
While parsing config: yaml: line 15: did not find expected key
While parsing config: yaml: line 15: did not find expected key
While parsing config: yaml: line 15: did not find expected key
While parsing config: yaml: line 15: did not find expected key
While parsing config: yaml: line 15: did not find expected key
While parsing config: yaml: line 15: did not find expected key
While parsing config: yaml: line 15: did not find expected key
While parsing config: yaml: line 15: did not find expected key
```

**To Reproduce**
1. What version of AdGuardHome sync used? version-v0.2.0
2. What version of AdGuardHome us used? v0.106.3
3. How does the configuration look? 
```
# cron expression to run in daemon mode. (default; "" = runs only once)
cron: "*/10 * * * *"

origin:
  # url of the origin instance
  url: http://10.0.2.254:3000
  # apiPath: define an api path if other than "/control"
  # insecureSkipVerify: true # disable tls check
  username: redacted
  password: redacted

# replica instance (optional, if only one)
replica:
  # url of the replica instance
        url: http://10.0.2.250:3000
  username: redacted
  password: redacted

# replicas instances (optional, if more than one)
replicas:
  # url of the replica instance
  #- url: http://192.168.1.3
  #  username: username
  #  password: password
  #- url: http://192.168.1.4
  #  username: username
  #  password: password

# Configure the sync API server, disabled if api port is 0
api:
  # Port, default 8080
  port: 8080
  # if username and password are defined, basic auth is applied to the sync API
  username: redacted
  password: redacted
  ```
4. What is the error message? `While parsing config: yaml: line 15: did not find expected key`

**Expected behavior**
A smooth sync between two adguard instances without any errors.

**Screenshots**
If applicable, add log files or json responses from AdGuardHome to help explain your problem.

**Additional context**
