### ISSUE TITLE
Default docker configuration not working

### ISSUE THREAD

**Issue by jcastro** [bakito/adguardhome-sync#398]
### What happened?

I had to remove the port 3000 on the ORIGIN URL variable in order to get it working. I was just wondering why all the examples use HTTPS and :3000 for the AdGuard IP?

### AdguardHome-Sync Version

0.6.12

### AdguardHome Version

0.107.52

### Configuration

```shell
Here's the code that's working for me!


version: "2.1"
services:
  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync
    container_name: adguardhome-sync
    command: run
    environment:
      TZ: Europe/Madrid
      LOG_LEVEL: info
      ORIGIN_URL: http://10.0.1.11
      ORIGIN_USERNAME: jonatan
      ORIGIN_PASSWORD: REDACTED
      REPLICA1_URL: http://10.0.1.12
      REPLICA1_USERNAME: jonatan
      REPLICA1_PASSWORD: REDACTED
      CRON: 0 */2 * * * # run every 10 minutes
      RUN_ON_START: "true"
      API_PORT: 8080
    ports:
      - 8080:8080
    restart: unless-stopped
networks: {}
```
```


### Relevant log output

```shell
Not needed
```

### Anything else?

Just trying to understand why on the Docker Compose version it's using HTTPS and adding the additional port 3000 if above says the instances should be initialized already!
```
environment:
      LOG_LEVEL: "info"
      ORIGIN_URL: "https://192.168.1.2:3000"
      ORIGIN_USERNAME: "username"
      ORIGIN_PASSWORD: "password"
      ```
