### ISSUE TITLE
Run on start ignored when API disabled

### ISSUE THREAD

**Issue by danieletorelli** [bakito/adguardhome-sync#473]
### What happened?

The sync doesn't happen on start but only in the next cron window.
If the API is enabled though, the sync happens on start.

### AdguardHome-Sync Version

0.6.16

### AdguardHome Version

0.107.55

### OS Information

Docker environment on Linux

### Configuration

```shell
CRON=0 */6 * * *
API_PORT=0
API_METRICS_ENABLED=false
```

### Relevant log output

```shell
2024-12-20T21:37:51.733Z	INFO	sync	sync/sync.go:38	AdGuardHome sync	{"version": "v0.6.16", "build": "2024-12-18T07:35:37Z", "os": "linux", "arch": "arm64"}
2024-12-20T21:37:51.734Z	INFO	sync	sync/sync.go:65	Setup cronjob	{"cron": "0 */6 * * *", "next-execution": "2024-12-21T00:00:00.000Z"}
```

**Comment by bakito** [comment]
Is `RUN_ON_START: "true"` set?

**Comment by danieletorelli** [comment]
> Is `RUN_ON_START: "true"` set?

Yes sorry, that part was unclear. Defining an explicit env variable in the config:
```
CRON=0 */6 * * *
API_PORT=0
API_METRICS_ENABLED=false
RUN_ON_START=true
```

still leads to:

```
2024-12-23T05:55:25.326Z	INFO	sync	sync/sync.go:38	AdGuardHome sync	{"version": "v0.6.16", "build": "2024-12-18T07:35:37Z", "os": "linux", "arch": "arm64"}
2024-12-23T05:55:25.328Z	INFO	sync	sync/sync.go:65	Setup cronjob	{"cron": "0 */6 * * *", "next-execution": "2024-12-23T06:00:00.000Z"}
```

but with:
```
CRON=0 */6 * * *
API_PORT=8080
API_METRICS_ENABLED=false
RUN_ON_START=true
```

it triggers correctly:
```
2024-12-23T05:57:56.672Z	INFO	sync	sync/sync.go:38	AdGuardHome sync	{"version": "v0.6.16", "build": "2024-12-18T07:35:37Z", "os": "linux", "arch": "arm64"}
2024-12-23T05:57:56.674Z	INFO	sync	sync/sync.go:65	Setup cronjob	{"cron": "0 */6 * * *", "next-execution": "2024-12-23T06:00:00.000Z"}
2024-12-23T05:57:56.674Z	INFO	sync	sync/http.go:86	Starting API server	{"port": 8080}
2024-12-23T05:57:56.674Z	INFO	sync	sync/sync.go:75	Running sync on startup
2024-12-23T05:57:57.180Z	INFO	sync	sync/sync.go:174	Connected to origin	{"from": "ns1.mydomain.com", "version": "v0.107.55"}
2024-12-23T05:57:59.308Z	INFO	sync	sync/sync.go:267	Start sync	{"from": "ns1.mydomain.com", "to": "ns2.mydomain.com"}
```

**Comment by bakito** [comment]
can you please provide tie full applied config?
Check here how to get it: https://github.com/bakito/adguardhome-sync/wiki/FAQ#how-to-print-the-current-applied-configuration

**Comment by danieletorelli** [comment]
> can you please provide tie full applied config? Check here how to get it: https://github.com/bakito/adguardhome-sync/wiki/FAQ#how-to-print-the-current-applied-configuration

```yaml
origin:
    url: https://ns1.mydomain.com
    webURL: https://ns1.mydomain.com
    apiPath: /control
    username: myusername
    password: mypassword
    insecureSkipVerify: false
    autoSetup: false
replicas:
    - url: https://ns2.mydomain.com
      webURL: https://ns2.mydomain.com
      apiPath: /control
      username: myusername
      password: mypassword
      insecureSkipVerify: false
      autoSetup: false
cron: 0 */6 * * *
runOnStart: true
printConfigOnly: true
features:
    dns:
        accessLists: true
        serverConfig: true
        rewrites: true
    dhcp:
        serverConfig: true
        staticLeases: true
    generalSettings: true
    queryLogConfig: true
    statsConfig: true
    clientSettings: true
    services: true
    filters: true
    theme: true
```
