### ISSUE TITLE
Synchronising custom DNS-Allowlists

### ISSUE THREAD

**Issue by LunarJetman0** [bakito/adguardhome-sync#513]
### Is your feature request related to a problem? Please describe.

I have Adguardhome-sync set up and sync'ing without any errors, however it doesn't appear to sync custom allow lists themselves. e.g. I have  the following section in my Adguard config yaml:
```
whitelist_filters:
  - enabled: true
    url: /opt/AdGuardHome/userfilters/adGuard_domainExceptions.txt
    name: My Custom Allowlist
    id: 1740147309
user_rules: []
```
This section gets sync'd but the file _/opt/AdGuardHome/userfilters/adGuard_domainExceptions.txt_ doesn't.

This means that I still need to modify that file on both the origin and replica servers for them to both allow the domains specified in this file.

### Describe the solution you'd like*

It would be great to be able to configure custom paths that are also sync'd as part of a sync job.

### Describe alternatives you've considered

Only alternative I can think of is an out-of-band process that copies the required file to the replica via scheduled (s)ftp
