### ISSUE TITLE
sync API server WebGUI WebGUI Not Reachable & Sync Issues

### ISSUE THREAD

**Issue by MarvinMynx** [bakito/adguardhome-sync#529]
### What happened?

Hey,

I think this is a very cool project, and it deserves more attention and support.

I have an issue where the WebGUI is not reachable. I set this up using the Docker Compose file and environment variables on CasaOS. The logs seem fine.

As mentioned in the title, the WebGUI is not accessible at all. And despite the logs, it seems like the sync is not working properly. For example, I don’t see the same query log on both AdGuard instances after the sync has happened.

I’d appreciate any help or pointers in the right direction! ^^"

Here is my config:
```yaml
name: amazing_chiahui
services:
  adguardhome-sync:
    cpu_shares: 90
    command: []
    container_name: adguardhome-sync
    deploy:
      resources:
        limits:
          memory: 4096M
    environment:
      - API_PORT=8080
      - CONTINUE_ON_ERROR=false
      - CRON=0 */2 * * *
      - FEATURES_CLIENT_SETTINGS=true
      - FEATURES_DHCP_SERVER_CONFIG=true
      - FEATURES_DHCP_STATIC_LEASES=true
      - FEATURES_DNS_ACCESS_LISTS=true
      - FEATURES_DNS_REWRITES=true
      - FEATURES_DNS_SERVER_CONFIG=true
      - FEATURES_FILTERS=true
      - FEATURES_GENERAL_SETTINGS=true
      - FEATURES_QUERY_LOG_CONFIG=true
      - FEATURES_SERVICES=true
      - FEATURES_STATS_CONFIG=true
      - FEATURES_THEME=true
      - LOG_LEVEL=info
      - ORIGIN_PASSWORD=redacted
      - ORIGIN_URL=http://redacted.126
      - ORIGIN_USERNAME=redacted
      - REPLICA1_PASSWORD=redacted
      - REPLICA1_URL=http://redacted.127
      - REPLICA1_USERNAME=redacted
      - RUN_ON_START=true
    hostname: adguardhome-sync
    image: ghcr.io/bakito/adguardhome-sync:latest
    labels:
      icon: https://icon.casaos.io/main/all/adguardhome-sync.png
    restart: unless-stopped
    ports: []
    volumes: []
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
```

### AdguardHome-Sync Version

[latest](https://github.com/users/bakito/packages/container/adguardhome-sync/374144309?tag=latest)
[v0.7.2](https://github.com/users/bakito/packages/container/adguardhome-sync/374144309?tag=v0.7.2)

### AdguardHome Version

Instance1: Version: v0.107.59
Instance2: Version: v0.107.59

### OS Information

It is running on Proxmox \ LXC \ CasaOS \ Docker Compose File. From where exactly wold i need to post `os-release` or `uname -m`?

### Configuration

```shell
ENV Vars in Compose File as Mentioned Above.
```

### Current Applied Configuration

```shell
The Container won't come up with PRINT_CONFIG_ONLY set to true.
```

### Relevant log output

```shell
adguardhome-sync  | 2025-03-21T19:58:35.103Z    INFO    sync    sync/sync.go:38    AdGuardHome sync    {"version": "v0.7.2", "build": "2025-03-14T07:16:57Z", "os": "linux", "arch": "amd64"}
adguardhome-sync  | 2025-03-21T19:58:35.104Z    INFO    sync    sync/sync.go:65    Setup cronjob    {"cron": "0 */2 * * *", "next-execution": "2025-03-21T20:00:00.000Z"}
adguardhome-sync  | 2025-03-21T19:58:35.104Z    INFO    sync    sync/http.go:95    Starting API server    {"port": 8080}
adguardhome-sync  | 2025-03-21T19:58:35.104Z    INFO    sync    sync/sync.go:87    Running sync on startup
adguardhome-sync  | 2025-03-21T19:58:35.244Z    INFO    sync    sync/sync.go:180    Connected to origin    {"from": "redacted.126", "version": "v0.107.59"}
adguardhome-sync  | 2025-03-21T19:58:36.462Z    INFO    sync    sync/sync.go:273    Start sync    {"from": "redacted.126", "to": "redacted.127"}
adguardhome-sync  | 2025-03-21T19:58:36.520Z    INFO    sync    sync/sync.go:281    Connected to replica    {"from": "redacted.126", "to": "redacted.127", "version": "v0.107.59"}
adguardhome-sync  | 2025-03-21T19:58:37.331Z    INFO    sync    sync/sync.go:311    Sync done    {"from": "redacted.126", "to": "redacted.127"}
```

### Anything else?

Is it normal that there is no Bash/sh/terminal/CLI access to the container? In the CasaOS terminal view (which I believe is the same as running docker exec -it <mycontainer> sh), I get the following error:
`OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown`
