### ISSUE TITLE
Certificate Error

### ISSUE THREAD

**Issue by nilava** [bakito/adguardhome-sync#55]
I am getting the following error.

But if you do open the url u can see its signed by a valid certificate

```
ERROR	sync	sync/sync.go:99	Error getting origin status	{"from": "adguard.ownlab.in", "error": "Get \"https://adguard.ownlab.in/control/status\": x509: certificate signed by unknown authority"}
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).sync
	/go/src/app/pkg/sync/sync.go:99
github.com/bakito/adguardhome-sync/pkg/sync.Sync.func3
	/go/src/app/pkg/sync/sync.go:61
```

My Docker Compose File

```
version: "3.2"

services:
  adguardhome-sync:
    image: quay.io/bakito/adguardhome-sync
    container_name: adguardhome-sync
    command: run
    environment:
      - ORIGIN_URL=https://adguard.ownlab.in
      - ORIGIN_USERNAME=SECRET
      - ORIGIN_PASSWORD=SECRET
      - REPLICA_URL=https://adguard-backup.ownlab.in
      - REPLICA_USERNAME=SECRET
      - REPLICA_PASSWORD=SECRET
      - CRON=*/10 * * * * # run every 10 minutes
      - RUNONSTART=true
    ports:
      - 8080:8080
    restart: unless-stopped
```
