### ISSUE TITLE
When using ALL DNS Settings turned on a few are missed when changed on the primary

### ISSUE THREAD

**Issue by pyrodex** [bakito/adguardhome-sync#63]
I tweaked a few settings on my primary and notice on the secondary DNS server running the same version after the sync was done the following settings are not changed:

```
root@dns02:~# diff /etc/adguard/config.yaml config.yaml
50c50
<   all_servers: true SECONDARY
---
>   all_servers: false PRIMARY
65c65
<   cache_optimistic: true SECONDARY
---
>   cache_optimistic: false PRIMARY
root@dns02:~#
```

From the SYNC config file:
```
# Configure sync features; by default all features are enabled.
features:
  generalSettings: true
  queryLogConfig: true
  statsConfig: true
  clientSettings: true
  services: true
  filters: true
  dhcp:
    serverConfig: false
    staticLeases: true
  dns:
    serverConfig: true
    accessLists: true
    rewrites: true
```

Running the latest version from Docker.
